on: [push]

jobs:
  setup-sfdx-action:
    runs-on: ubuntu-latest
    name: Setup SFDX
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SFDX
        uses: ./
        with:
          plugins: skuid-sfdx
